### ISSUE TITLE
Enabling parallel build on windows

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt#410]
### Discussed in https://github.com/eclipse-cdt/cdt/discussions/408

<div type='discussions-op-text'>

<sup>Originally posted by **giuliof** June  7, 2023</sup>
Hello,
I'm currently having an issue with Eclipse CDT version 2023-03 on windows and some "C Managed Build" projects. In the C/C++ Build > Behavior tab I have "Enable parallel build" checked with "Use optimal jobs". But when the project is built, files are processed sequentially and complete operation takes over one minute.
If I select "Use unlimited jobs" the build operation is run in parallel and takes only few seconds.

I have no issue on Linux platform, nor on an older Eclipse version, CDT 8.3.0, where some of the projects were created.

I may fall back to "Use unlimited jobs" option, but I feel there is a most efficient way to solve this problem.</div>

In the discussion we discovered that the issue is the fix for [Bug 573502](https://bugs.eclipse.org/bugs/show_bug.cgi?id=573502) causes CDT to have sub-make where it didn't use to. `-j N` for parallel execution on Windows isn't [supported](https://www.gnu.org/software/make/manual/make.html):

> If you set it to some numeric value ‘N’ and your operating system supports it (most any UNIX system will; others typically won’t), the parent make and all the sub-makes will communicate to ensure that there are only ‘N’ jobs running at the same time between them all.

This issue is to try to resolve the performance regression introduced by the fix for [Bug 573502](https://bugs.eclipse.org/bugs/show_bug.cgi?id=573502)

cc: @Torbjorn-Svensson

**Comment by jantje** [comment]
My 2 cent
Repeat the -j N in the makefile on windows

**Comment by Torbjorn-Svensson** [comment]
What version of make is used and is there something that can be done to fix the issue in the source code of make rather than putting another bandied in the makefile?

**Comment by jantje** [comment]
My 2 cent: It is complicated.
1) I think the pre [Bug 573502](https://bugs.eclipse.org/bugs/show_bug.cgi?id=573502) code having post/pre commands will have the exact same issue.
2) I think [Bug 573502](https://bugs.eclipse.org/bugs/show_bug.cgi?id=573502) was not a bug but should have been fixed by a new toolchain (extra tool ) or with extra recipes for some tools. (Like Sloeber does to convert an .elf file to a .bin or a .hex file.)
![afbeelding](https://github.com/eclipse-cdt/cdt/assets/1175841/7f663696-1a26-45fa-beaf-3d9bd7faa359)

**Comment by Torbjorn-Svensson** [comment]
@jantje this is how the toolchain integration looks like, but try to add a post-build command that uses the result of the objcopy command and you will see that without 043651694af50a5de274bafb9560c93b6b13727b, your post-build command will be executed before/in parallel with your objcopy tool.

**Comment by jonahgraham** [comment]
> What version of make is used and is there something that can be done to fix the issue in the source code of make rather than putting another bandied in the makefile?

The lack of this feature on Windows (mingw) is a long term known issue, so I assume that if it was solvable it would have been already. On Windows Cygwin (IIUC) make does support `-jN` when using submakes.

The current solution is preferring correctness over performance. The question is can we rework dependencies in makefiles to not have to use sub-makes as that would resolve the issue.

I am missing part of the picture here, [Bug 573502](https://bugs.eclipse.org/bugs/show_bug.cgi?id=573502) covered the case of secondary outputs, but AFAICT there are no examples of that in CDT's main test code for a toolchain that has such secondary outputs. Can someone point me at such an example that I can add to the CDT test cases?

**Comment by jantje** [comment]
> @jantje this is how the toolchain integration looks like, but try to add a post-build command that uses the result of the objcopy command and you will see that without [0436516](https://github.com/eclipse-cdt/cdt/commit/043651694af50a5de274bafb9560c93b6b13727b), your post-build command will be executed before/in parallel with your objcopy tool.

I'm not saying you are wrong but in the Sloeber case the print toolsize sometimes uses the result of the objcopy.
I guess the problem you had was a tool that started a tool assynchronously.

**Comment by jantje** [comment]
>The current solution is preferring correctness over performance. The question is can we rework dependencies in makefiles to not have to use sub-makes as that would resolve the issue.

It is the advice I found for using pre and post processing using makefiles. The more I understand about make the more it makes sense.
As I stated before it is also the way managed build external build has done this for years.
I think managed build using external builder with pre/post commands with gnu make on windows has not been compatible with parallel build for years. (I hope I worded that correctly 😄  )

**Comment by jantje** [comment]
>Okay, now I see what the confusion is.

If there is any confusion this is not the confusion here.
What I understand you are saying is this: If a target contains multiple recipes and a recipe is a ${MAKE} the next recipe is executed before the last recipe of the last make rule of the ${MAKE} recipe is finished.
Given how make works and is dependent on previous recipes being finished before starting others .... it is hard to believe this is general make behaviour.

**Comment by jantje** [comment]
Rereading again:
Maybe there is some confusion about "secondary outputs" what exactly (in make terms) do you mean by that?

**Comment by Torbjorn-Svensson** [comment]
> > What version of make is used and is there something that can be done to fix the issue in the source code of make rather than putting another bandied in the makefile?
> 
> The lack of this feature on Windows (mingw) is a long term known issue, so I assume that if it was solvable it would have been already. On Windows Cygwin (IIUC) make does support `-jN` when using submakes.
> 
> The current solution is preferring correctness over performance. The question is can we rework dependencies in makefiles to not have to use sub-makes as that would resolve the issue.
> 
> I am missing part of the picture here, [Bug 573502](https://bugs.eclipse.org/bugs/show_bug.cgi?id=573502) covered the case of secondary outputs, but AFAICT there are no examples of that in CDT's main test code for a toolchain that has such secondary outputs. Can someone point me at such an example that I can add to the CDT test cases?

So, the scenario is quite simple.
The toolchain definition produces an artifact.
One of the tools in the toolchain produces an artifact that is marked as a secondary output and takes the primary output as input.
Then in the project, the user has set a post-build step that will take the secondary output artifact as input and do something with it.

A concrete example:
1.  The toolchain definition has a tool produces an .elf binary and the tool is listed as a `targetTool` on the `toolChain` node.
2. The toolchain definition has a tool that takes the .elf file and converts it to a .hex file by calling objcopy. This objcopy tool has an `outputType` that is listed in the field `secondaryOutput` on the `toolChain` node.
3. The project has defined a post-build step that consumes the .hex file and counts the number of lines in it. (Silly, but something...  😄)

> Rereading again: Maybe there is some confusion about "secondary outputs" what exactly (in make terms) do you mean by that?

This what I'm refering to by "secondary outputs":
![image](https://github.com/eclipse-cdt/cdt/assets/50025045/ab2b4d96-b482-4f25-b1d4-6ebc86e536b9)

@jonahgraham this is actually the only test case I can find in the CDT tree that has defined some secondary output. The managed build revision is set to 3.0.0, but I guess it does not matter for this particular problem. The screenshot still indicates where it's set.
Do you see any good way to test this in CI?

**Comment by Torbjorn-Svensson** [comment]
> The lack of this feature on Windows (mingw) is a long term known issue, so I assume that if it was solvable it would have been already. On Windows Cygwin (IIUC) make does support `-jN` when using submakes.

I'm sorry to be picky here, but the above statement is simply not true, at least not for the make.exe that I build when cross compiling for Windows on Linux.

I've tested it using the following Makefile:
```makefile
TARGETS := $(addsuffix .stamp,1 2 3 4 5 6 7 8 9 10)

all:
	+@$(MAKE) --no-print-directory main-build && $(MAKE) --no-print-directory post-build

main-build: $(TARGETS)

%.stamp:
	./foo.exe $@

post-build:
	@echo "post-build"

.PHONY: all main-build post-build
```

The "foo.exe" application is this:
```c
#include <stdio.h>
#include <windows.h>
#include <process.h>
int main(int argc, char *argv[]) {
  printf("Started %s %s as pid %d\n", argv[0], argv[1], _getpid());
  Sleep(5*1000);
  printf("Finished %s %s with pid %d\n", argv[0], argv[1], _getpid());
  return 0;
}

```


And the output running the above in CMD without any sh.exe on path is:
```
C:\dev\make>.\make.exe -r -j4
./foo.exe 1.stamp
./foo.exe 2.stamp
./foo.exe 3.stamp
Started ./foo.exe 1.stamp as pid 112088
./foo.exe 4.stamp
Started ./foo.exe 2.stamp as pid 115060
Started ./foo.exe 3.stamp as pid 108264
Started ./foo.exe 4.stamp as pid 107460
Finished ./foo.exe 1.stamp with pid 112088
./foo.exe 5.stamp
Started ./foo.exe 5.stamp as pid 98996
Finished ./foo.exe 4.stamp with pid 107460
Finished ./foo.exe 3.stamp with pid 108264
Finished ./foo.exe 2.stamp with pid 115060
./foo.exe 6.stamp
./foo.exe 7.stamp
Started ./foo.exe 6.stamp as pid 115804
./foo.exe 8.stamp
Started ./foo.exe 7.stamp as pid 94932
Started ./foo.exe 8.stamp as pid 116724
Finished ./foo.exe 5.stamp with pid 98996
./foo.exe 9.stamp
Started ./foo.exe 9.stamp as pid 96600
Finished ./foo.exe 6.stamp with pid 115804
./foo.exe 10.stamp
Finished ./foo.exe 7.stamp with pid 94932
Started ./foo.exe 10.stamp as pid 113032
Finished ./foo.exe 8.stamp with pid 116724
Finished ./foo.exe 9.stamp with pid 96600
Finished ./foo.exe 10.stamp with pid 113032
"post-build"

C:\dev\make>.\make --version
GNU Make 4.2.1
Built for x86_64-w64-mingw32
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

C:\dev\make>
```

To me, this looks to be working just fine, or am I missing something here?

**Comment by jonahgraham** [comment]
> I'm sorry to be picky here

Not picky  :-) Thank you for verifying this.

> To me, this looks to be working just fine, or am I missing something here?

I don't know - your example seems correct to me. Maybe the make docs are out of date and it has been fixed on Windows. I'll try to reproduce before I change any of the makefile generation

@giuliof can you share the `make --version` that you are seeing issues with?

**Comment by jantje** [comment]
I learned a lot today. Thanks for that.
I still don't understand why secondary targets may not have been build when using
```
$(MAKE) --no-print-directory main-build
$(MAKE) --no-print-directory post-build
```
but are guaranteed to be build when using
`+@$(MAKE) --no-print-directory main-build && $(MAKE) --no-print-directory post-build`
Which is IMHO basically what the fix for [Bug 573502](https://bugs.eclipse.org/bugs/show_bug.cgi?id=573502) changed.

Seems there is still more to learn about make.

**Comment by jonahgraham** [comment]
That isn't what was changed.

See https://git.eclipse.org/r/c/cdt/org.eclipse.cdt/+/180528/6/build/org.eclipse.cdt.managedbuilder.core.tests/resources/test30Projects/preAndPostBuildSteps/Benchmarks/makefile for an example.

**Comment by jantje** [comment]
Now it makes sense.
The post build was part of the Main-build and as such can/will be triggered before the secondary.
That was indeed a bug and the fix correctly fixed it. I thought it was like that so sorry for that confusion.

I'm not sure why the change uses the &&.
I think it is less readable. (Asking to know whether I should use && in autoBuild)

**Comment by Torbjorn-Svensson** [comment]
> I'm not sure why the change uses the &&. I think it is less readable. (Asking to know whether I should use && in autoBuild)

I agree that it might be a bit less readable. Right now, I don't remember the reason for it, but I think it had something to do with how the job-server thingy works. After all, it's over 2 years ago since I upstreamed the fix and before that, the fix was internal for another few years...

You can play with this and if you find a more readable way to express the same thing and with the same behavior, then please create a PR for it.

**Comment by jonahgraham** [comment]
Make 3.81 was released in 2006 and if by GnuWin32 you mean https://gnuwin32.sourceforge.net/ that seems to have been last released in 2010.

Thanks @Torbjorn-Svensson for verifying this on the newer (but still old 4.2.1 that was released all the way back in 2016). I guess make manual wasn't updated when someone improved the make behaviour. 

@giuliof I am inclined to close this with no further changes planned. Let me know if you think I misunderstood something, or if you can reproduce the problem in more recent make. If someone is still shipping such an old version of make, I recommend that you file a bug with them asking them to modernize.

FWIW I understand in embedded the desire to keep tool versions stable for many years. But as the fix in this case was to fix a correctness issue that takes precedence IMHO.

**Comment by giuliof** [comment]
No problem, I will move on to newer make. I've tried with the latest one and I have no issues.
Thanks for the support!

**Comment by jonahgraham** [comment]
Thanks @giuliof for reporting back

**Comment by Torbjorn-Svensson** [comment]
> No problem, I will move on to newer make. I've tried with the latest one (GNU Make 4.4.90) and I have no issues. Thanks for the support!

Just a small remark. 4.4.90 is a pre-release and might not be stable. 
Right now, the last stable release is 4.4.1.
